language: node_js
node_js:
  - 0.8
services: 
  - mongodb
  - redis-server

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: npm test && node_modules/.bin/cucumber.js