language: node_js
node_js:
  - 0.10
  - iojs-v1.0.4

cache:
  directories:
    - node_modules

services: 
  - mongodb
  - redis-server

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: 
  - npm test
  - npm run cover-cukes